### ISSUE TITLE
Issue error PHP 7.1

### ISSUE THREAD

**Issue by winbotscript** [rl404/MAL-Scraper-API#4]
Hello there,

Issue error <br />
<b>Warning</b>:  mkdir(): Permission denied in <b>/home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php</b> on line <b>279</b><br />
<br />
<b>Fatal error</b>:  Uncaught Exception: Unable to create cache directory /home/admin/domain/api/anime/vendor/rl404/mal-scraper/src/MalScraper/Cache/ in /home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php:280
Stack trace:
#0 /home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php(235): Cache-&gt;_checkCacheDir()
#1 /home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php(219): Cache-&gt;getCacheDir()
#2 /home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php(177): Cache-&gt;_loadCache()
#3 /home/admin/domain/api/anime/vendor/rl404/mal-scraper/src/MalScraper/MalScraper.php(141): Cache-&gt;eraseExpired(3600)
#4 /home/admin/domain/api/anime/index.php(43): MalScraper\MalScraper-&gt;__call('getInfo', Array)
#5 {main}
  thrown in <b>/home/admin/domain/api/anime/vendor/rl404/simple-php-cache/cache.class.php</b> on line <b>280</b><br />

I try it in PHP 7.1

**Comment by rl404** [comment]
Hi there,

This error happens when mal-scraper library doesn't have permission to create folder for the cache.
There are 2 ways to fix this.
1. Create folder `Cache` in `/vendor/rl404/mal-scraper/src/MalScraper` and run `chmod 775 Cache`
2. Give vendor permission by `chmod 775 vendor`

If you have another way other than these 2 to fix the permission, then you can try it by yourself.

**Comment by winbotscript** [comment]
Ok thx for your help, GBU
